name: GitHub Release

on:
  workflow_run:
    workflows: [CI]
    branches: [master]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  call-workflow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: palashmon/reusable-workflows/.github/workflows/gh-release.yml@main
    with:
      branch_name: 'master'
